//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Project</summary>
	[PublishedModel("project")]
	public partial class Project : PublishedContentModel, IProjectSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public new const string ModelTypeAlias = "project";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Project, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Project(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Address Contact: Enter address contact
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("addressContact")]
		public string AddressContact => this.Value<string>("addressContact");

		///<summary>
		/// Birth Day
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("birthDay")]
		public string BirthDay => this.Value<string>("birthDay");

		///<summary>
		/// Created Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("createdDate")]
		public global::System.DateTime CreatedDate => this.Value<global::System.DateTime>("createdDate");

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("description")]
		public string Description => this.Value<string>("description");

		///<summary>
		/// Email contact
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("emailContact")]
		public string EmailContact => this.Value<string>("emailContact");

		///<summary>
		/// Google Map: Please insert link url iframe on google map
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("googleMap")]
		public string GoogleMap => this.Value<string>("googleMap");

		///<summary>
		/// Image Root: Please insert image with witdh: 300 px and Height: 300px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("imageRoot")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent ImageRoot => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("imageRoot");

		///<summary>
		/// Images: Please insert image with width: 700px and height: 300px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("images")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent> Images => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>>("images");

		///<summary>
		/// Name contact
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("nameContact")]
		public string NameContact => this.Value<string>("nameContact");

		///<summary>
		/// Name Project
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("nameProject")]
		public string NameProject => this.Value<string>("nameProject");

		///<summary>
		/// Name Project Non Unicode: Nhập tên dự án không dấu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("nameProjectNonUnicode")]
		public string NameProjectNonUnicode => this.Value<string>("nameProjectNonUnicode");

		///<summary>
		/// Overview: Tổng quan dự án
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("overview")]
		public global::System.Web.IHtmlString Overview => this.Value<global::System.Web.IHtmlString>("overview");

		///<summary>
		/// Phone Contact
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("phoneContact")]
		public string PhoneContact => this.Value<string>("phoneContact");

		///<summary>
		/// Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("type")]
		public string Type => this.Value<string>("type");

		///<summary>
		/// Acreage: diện tích (đơn vị m2)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("acreage")]
		public string Acreage => global::Umbraco.Web.PublishedModels.ProjectSettings.GetAcreage(this);

		///<summary>
		/// Acreage Filter: diện tích hỗ trợ filter
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("acreageFilter")]
		public string AcreageFilter => global::Umbraco.Web.PublishedModels.ProjectSettings.GetAcreageFilter(this);

		///<summary>
		/// Facade: mặt tiền
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("facade")]
		public string Facade => global::Umbraco.Web.PublishedModels.ProjectSettings.GetFacade(this);

		///<summary>
		/// Facing House: Chọn hướng nhà
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("facingHouse")]
		public string FacingHouse => global::Umbraco.Web.PublishedModels.ProjectSettings.GetFacingHouse(this);

		///<summary>
		/// Number of bedrooms: Số phòng ngủ
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("numberOfBedrooms")]
		public string NumberOfBedrooms => global::Umbraco.Web.PublishedModels.ProjectSettings.GetNumberOfBedrooms(this);

		///<summary>
		/// Price: đơn vị VNĐ (có thể nhập số ước tính, rồi thương lượng)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("price")]
		public string Price => global::Umbraco.Web.PublishedModels.ProjectSettings.GetPrice(this);

		///<summary>
		/// Price Filter: hổ trợ chọn giá trong việc filter
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("priceFilter")]
		public string PriceFilter => global::Umbraco.Web.PublishedModels.ProjectSettings.GetPriceFilter(this);

		///<summary>
		/// The district: Chọn quận/huyện
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("theDistrict")]
		public string TheDistrict => global::Umbraco.Web.PublishedModels.ProjectSettings.GetTheDistrict(this);

		///<summary>
		/// Type House: chọn loại nhà
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("typeHouse")]
		public string TypeHouse => global::Umbraco.Web.PublishedModels.ProjectSettings.GetTypeHouse(this);

		///<summary>
		/// Type Property: loại bất động sản
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("typeProperty")]
		public string TypeProperty => global::Umbraco.Web.PublishedModels.ProjectSettings.GetTypeProperty(this);

		///<summary>
		/// World Highway: Lộ giới
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("worldHighway")]
		public string WorldHighway => global::Umbraco.Web.PublishedModels.ProjectSettings.GetWorldHighway(this);
	}
}
