//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "projectSettings"
	/// <summary>Project Settings</summary>
	public partial interface IProjectSettings : IPublishedContent
	{
		/// <summary>Acreage</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		string Acreage { get; }

		/// <summary>Acreage Filter</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		string AcreageFilter { get; }

		/// <summary>Facade</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		string Facade { get; }

		/// <summary>Facing House</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		string FacingHouse { get; }

		/// <summary>Number of bedrooms</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		string NumberOfBedrooms { get; }

		/// <summary>Price</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		string Price { get; }

		/// <summary>Price Filter</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		string PriceFilter { get; }

		/// <summary>The district</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		string TheDistrict { get; }

		/// <summary>Type House</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		string TypeHouse { get; }

		/// <summary>Type Property</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		string TypeProperty { get; }

		/// <summary>World Highway</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		string WorldHighway { get; }
	}

	/// <summary>Project Settings</summary>
	[PublishedModel("projectSettings")]
	public partial class ProjectSettings : PublishedContentModel, IProjectSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public new const string ModelTypeAlias = "projectSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProjectSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ProjectSettings(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Acreage: diện tích (đơn vị m2)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("acreage")]
		public string Acreage => GetAcreage(this);

		/// <summary>Static getter for Acreage</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public static string GetAcreage(IProjectSettings that) => that.Value<string>("acreage");

		///<summary>
		/// Acreage Filter: diện tích hỗ trợ filter
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("acreageFilter")]
		public string AcreageFilter => GetAcreageFilter(this);

		/// <summary>Static getter for Acreage Filter</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public static string GetAcreageFilter(IProjectSettings that) => that.Value<string>("acreageFilter");

		///<summary>
		/// Facade: mặt tiền
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("facade")]
		public string Facade => GetFacade(this);

		/// <summary>Static getter for Facade</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public static string GetFacade(IProjectSettings that) => that.Value<string>("facade");

		///<summary>
		/// Facing House: Chọn hướng nhà
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("facingHouse")]
		public string FacingHouse => GetFacingHouse(this);

		/// <summary>Static getter for Facing House</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public static string GetFacingHouse(IProjectSettings that) => that.Value<string>("facingHouse");

		///<summary>
		/// Number of bedrooms: Số phòng ngủ
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("numberOfBedrooms")]
		public string NumberOfBedrooms => GetNumberOfBedrooms(this);

		/// <summary>Static getter for Number of bedrooms</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public static string GetNumberOfBedrooms(IProjectSettings that) => that.Value<string>("numberOfBedrooms");

		///<summary>
		/// Price: đơn vị VNĐ (có thể nhập số ước tính, rồi thương lượng)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("price")]
		public string Price => GetPrice(this);

		/// <summary>Static getter for Price</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public static string GetPrice(IProjectSettings that) => that.Value<string>("price");

		///<summary>
		/// Price Filter: hổ trợ chọn giá trong việc filter
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("priceFilter")]
		public string PriceFilter => GetPriceFilter(this);

		/// <summary>Static getter for Price Filter</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public static string GetPriceFilter(IProjectSettings that) => that.Value<string>("priceFilter");

		///<summary>
		/// The district: Chọn quận/huyện
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("theDistrict")]
		public string TheDistrict => GetTheDistrict(this);

		/// <summary>Static getter for The district</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public static string GetTheDistrict(IProjectSettings that) => that.Value<string>("theDistrict");

		///<summary>
		/// Type House: chọn loại nhà
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("typeHouse")]
		public string TypeHouse => GetTypeHouse(this);

		/// <summary>Static getter for Type House</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public static string GetTypeHouse(IProjectSettings that) => that.Value<string>("typeHouse");

		///<summary>
		/// Type Property: loại bất động sản
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("typeProperty")]
		public string TypeProperty => GetTypeProperty(this);

		/// <summary>Static getter for Type Property</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public static string GetTypeProperty(IProjectSettings that) => that.Value<string>("typeProperty");

		///<summary>
		/// World Highway: Lộ giới
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("worldHighway")]
		public string WorldHighway => GetWorldHighway(this);

		/// <summary>Static getter for World Highway</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public static string GetWorldHighway(IProjectSettings that) => that.Value<string>("worldHighway");
	}
}
